package com.sistemas.educatic.pojo;
// Generated Jan 13, 2016 4:10:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int id;
     private String denominacion;
     private byte tipoCurso;
     private Byte estado;
     private String descripcion;
     private Integer observacion;
     private Set gradoCursos = new HashSet(0);

    public Curso() {
    }

	
    public Curso(int id, String denominacion, byte tipoCurso) {
        this.id = id;
        this.denominacion = denominacion;
        this.tipoCurso = tipoCurso;
    }
    public Curso(int id, String denominacion, byte tipoCurso, Byte estado, String descripcion, Integer observacion, Set gradoCursos) {
       this.id = id;
       this.denominacion = denominacion;
       this.tipoCurso = tipoCurso;
       this.estado = estado;
       this.descripcion = descripcion;
       this.observacion = observacion;
       this.gradoCursos = gradoCursos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public byte getTipoCurso() {
        return this.tipoCurso;
    }
    
    public void setTipoCurso(byte tipoCurso) {
        this.tipoCurso = tipoCurso;
    }
    public Byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(Byte estado) {
        this.estado = estado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(Integer observacion) {
        this.observacion = observacion;
    }
    public Set getGradoCursos() {
        return this.gradoCursos;
    }
    
    public void setGradoCursos(Set gradoCursos) {
        this.gradoCursos = gradoCursos;
    }




}


