package com.sistemas.educatic.pojo;
// Generated Jan 13, 2016 4:10:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DocenteGrado generated by hbm2java
 */
public class DocenteGrado  implements java.io.Serializable {


     private int id;
     private Docente docente;
     private Grado grado;
     private Date fecha;
     private int gradoTutorId;
     private int gradoTutorPersonaId;
     private int gradoMatriculaId;

    public DocenteGrado() {
    }

    public DocenteGrado(int id, Docente docente, Grado grado, Date fecha, int gradoTutorId, int gradoTutorPersonaId, int gradoMatriculaId) {
       this.id = id;
       this.docente = docente;
       this.grado = grado;
       this.fecha = fecha;
       this.gradoTutorId = gradoTutorId;
       this.gradoTutorPersonaId = gradoTutorPersonaId;
       this.gradoMatriculaId = gradoMatriculaId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getGradoTutorId() {
        return this.gradoTutorId;
    }
    
    public void setGradoTutorId(int gradoTutorId) {
        this.gradoTutorId = gradoTutorId;
    }
    public int getGradoTutorPersonaId() {
        return this.gradoTutorPersonaId;
    }
    
    public void setGradoTutorPersonaId(int gradoTutorPersonaId) {
        this.gradoTutorPersonaId = gradoTutorPersonaId;
    }
    public int getGradoMatriculaId() {
        return this.gradoMatriculaId;
    }
    
    public void setGradoMatriculaId(int gradoMatriculaId) {
        this.gradoMatriculaId = gradoMatriculaId;
    }




}


