package com.sistemas.educatic.pojo;
// Generated Jan 13, 2016 4:10:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GradoCurso generated by hbm2java
 */
public class GradoCurso  implements java.io.Serializable {


     private int id;
     private Curso curso;
     private Grado grado;
     private Horario horario;
     private Date fecha;
     private Set tareas = new HashSet(0);
     private Set rendimientos = new HashSet(0);

    public GradoCurso() {
    }

	
    public GradoCurso(int id, Curso curso, Grado grado, Horario horario, Date fecha) {
        this.id = id;
        this.curso = curso;
        this.grado = grado;
        this.horario = horario;
        this.fecha = fecha;
    }
    public GradoCurso(int id, Curso curso, Grado grado, Horario horario, Date fecha, Set tareas, Set rendimientos) {
       this.id = id;
       this.curso = curso;
       this.grado = grado;
       this.horario = horario;
       this.fecha = fecha;
       this.tareas = tareas;
       this.rendimientos = rendimientos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Set tareas) {
        this.tareas = tareas;
    }
    public Set getRendimientos() {
        return this.rendimientos;
    }
    
    public void setRendimientos(Set rendimientos) {
        this.rendimientos = rendimientos;
    }




}


