package com.sistemas.educatic.pojo;
// Generated Jan 13, 2016 4:10:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Grado generated by hbm2java
 */
public class Grado  implements java.io.Serializable {


     private int id;
     private Matricula matricula;
     private Tutor tutor;
     private String denominacion;
     private char seccion;
     private byte estado;
     private Date anio;
     private String observacion;
     private String turno;
     private byte maxAlumno;
     private Set docenteGrados = new HashSet(0);
     private Set gradoCursos = new HashSet(0);

    public Grado() {
    }

	
    public Grado(int id, Matricula matricula, Tutor tutor, String denominacion, char seccion, byte estado, Date anio, String turno, byte maxAlumno) {
        this.id = id;
        this.matricula = matricula;
        this.tutor = tutor;
        this.denominacion = denominacion;
        this.seccion = seccion;
        this.estado = estado;
        this.anio = anio;
        this.turno = turno;
        this.maxAlumno = maxAlumno;
    }
    public Grado(int id, Matricula matricula, Tutor tutor, String denominacion, char seccion, byte estado, Date anio, String observacion, String turno, byte maxAlumno, Set docenteGrados, Set gradoCursos) {
       this.id = id;
       this.matricula = matricula;
       this.tutor = tutor;
       this.denominacion = denominacion;
       this.seccion = seccion;
       this.estado = estado;
       this.anio = anio;
       this.observacion = observacion;
       this.turno = turno;
       this.maxAlumno = maxAlumno;
       this.docenteGrados = docenteGrados;
       this.gradoCursos = gradoCursos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public Tutor getTutor() {
        return this.tutor;
    }
    
    public void setTutor(Tutor tutor) {
        this.tutor = tutor;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public char getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(char seccion) {
        this.seccion = seccion;
    }
    public byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }
    public Date getAnio() {
        return this.anio;
    }
    
    public void setAnio(Date anio) {
        this.anio = anio;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getTurno() {
        return this.turno;
    }
    
    public void setTurno(String turno) {
        this.turno = turno;
    }
    public byte getMaxAlumno() {
        return this.maxAlumno;
    }
    
    public void setMaxAlumno(byte maxAlumno) {
        this.maxAlumno = maxAlumno;
    }
    public Set getDocenteGrados() {
        return this.docenteGrados;
    }
    
    public void setDocenteGrados(Set docenteGrados) {
        this.docenteGrados = docenteGrados;
    }
    public Set getGradoCursos() {
        return this.gradoCursos;
    }
    
    public void setGradoCursos(Set gradoCursos) {
        this.gradoCursos = gradoCursos;
    }




}


