package com.sistemas.educatic.pojo;
// Generated Jan 13, 2016 4:10:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modalidadingreso generated by hbm2java
 */
public class Modalidadingreso  implements java.io.Serializable {


     private int id;
     private String denominacion;
     private String descripcion;
     private String observacion;
     private Byte estado;
     private Set matriculas = new HashSet(0);

    public Modalidadingreso() {
    }

	
    public Modalidadingreso(int id) {
        this.id = id;
    }
    public Modalidadingreso(int id, String denominacion, String descripcion, String observacion, Byte estado, Set matriculas) {
       this.id = id;
       this.denominacion = denominacion;
       this.descripcion = descripcion;
       this.observacion = observacion;
       this.estado = estado;
       this.matriculas = matriculas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(Byte estado) {
        this.estado = estado;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


