package com.sistemas.educatic.pojo;
// Generated Jan 13, 2016 4:10:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Permiso generated by hbm2java
 */
public class Permiso  implements java.io.Serializable {


     private int id;
     private String denominacion;
     private String estado;
     private Set usuarioPermisos = new HashSet(0);

    public Permiso() {
    }

	
    public Permiso(int id, String denominacion, String estado) {
        this.id = id;
        this.denominacion = denominacion;
        this.estado = estado;
    }
    public Permiso(int id, String denominacion, String estado, Set usuarioPermisos) {
       this.id = id;
       this.denominacion = denominacion;
       this.estado = estado;
       this.usuarioPermisos = usuarioPermisos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getUsuarioPermisos() {
        return this.usuarioPermisos;
    }
    
    public void setUsuarioPermisos(Set usuarioPermisos) {
        this.usuarioPermisos = usuarioPermisos;
    }




}


