package com.sistemas.educatic.pojo;
// Generated Jan 13, 2016 4:10:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private String dni;
     private String direccion;
     private int edad;
     private byte sexo;
     private String observacion;
     private int idUsuario;
     private byte estado;
     private Set telefonos = new HashSet(0);
     private Set tutors = new HashSet(0);
     private Set apoderados = new HashSet(0);
     private Set archivoimagens = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set docentes = new HashSet(0);
     private Set estudiantes = new HashSet(0);

    public Persona() {
    }

	
    public Persona(int id, String nombre, String apaterno, String amaterno, String dni, String direccion, int edad, byte sexo, int idUsuario, byte estado) {
        this.id = id;
        this.nombre = nombre;
        this.apaterno = apaterno;
        this.amaterno = amaterno;
        this.dni = dni;
        this.direccion = direccion;
        this.edad = edad;
        this.sexo = sexo;
        this.idUsuario = idUsuario;
        this.estado = estado;
    }
    public Persona(int id, String nombre, String apaterno, String amaterno, String dni, String direccion, int edad, byte sexo, String observacion, int idUsuario, byte estado, Set telefonos, Set tutors, Set apoderados, Set archivoimagens, Set usuarios, Set docentes, Set estudiantes) {
       this.id = id;
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.dni = dni;
       this.direccion = direccion;
       this.edad = edad;
       this.sexo = sexo;
       this.observacion = observacion;
       this.idUsuario = idUsuario;
       this.estado = estado;
       this.telefonos = telefonos;
       this.tutors = tutors;
       this.apoderados = apoderados;
       this.archivoimagens = archivoimagens;
       this.usuarios = usuarios;
       this.docentes = docentes;
       this.estudiantes = estudiantes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public byte getSexo() {
        return this.sexo;
    }
    
    public void setSexo(byte sexo) {
        this.sexo = sexo;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }
    public Set getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set telefonos) {
        this.telefonos = telefonos;
    }
    public Set getTutors() {
        return this.tutors;
    }
    
    public void setTutors(Set tutors) {
        this.tutors = tutors;
    }
    public Set getApoderados() {
        return this.apoderados;
    }
    
    public void setApoderados(Set apoderados) {
        this.apoderados = apoderados;
    }
    public Set getArchivoimagens() {
        return this.archivoimagens;
    }
    
    public void setArchivoimagens(Set archivoimagens) {
        this.archivoimagens = archivoimagens;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set docentes) {
        this.docentes = docentes;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }




}


