package com.sistemas.educatic.pojo;
// Generated Jan 13, 2016 4:10:46 PM by Hibernate Tools 4.3.1



/**
 * Telefono generated by hbm2java
 */
public class Telefono  implements java.io.Serializable {


     private int id;
     private Persona persona;
     private String denominacion;
     private String numero;
     private String observacion;
     private byte estado;

    public Telefono() {
    }

	
    public Telefono(int id, Persona persona, String numero, byte estado) {
        this.id = id;
        this.persona = persona;
        this.numero = numero;
        this.estado = estado;
    }
    public Telefono(int id, Persona persona, String denominacion, String numero, String observacion, byte estado) {
       this.id = id;
       this.persona = persona;
       this.denominacion = denominacion;
       this.numero = numero;
       this.observacion = observacion;
       this.estado = estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }




}


