package com.sistemas.educatic.pojo;
// Generated Jan 13, 2016 4:10:46 PM by Hibernate Tools 4.3.1



/**
 * UsuarioPermiso generated by hbm2java
 */
public class UsuarioPermiso  implements java.io.Serializable {


     private int id;
     private Permiso permiso;
     private Usuario usuario;
     private String url;
     private byte estado;

    public UsuarioPermiso() {
    }

    public UsuarioPermiso(int id, Permiso permiso, Usuario usuario, String url, byte estado) {
       this.id = id;
       this.permiso = permiso;
       this.usuario = usuario;
       this.url = url;
       this.estado = estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Permiso getPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(Permiso permiso) {
        this.permiso = permiso;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }




}


