package com.sistemas.educatic.pojo;
// Generated Jan 13, 2016 4:10:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private Persona persona;
     private String usuario;
     private String pasword;
     private String estado;
     private Date fechaRegistro;
     private Set usuarioPermisos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id, Persona persona, String usuario, String pasword, String estado, Date fechaRegistro) {
        this.id = id;
        this.persona = persona;
        this.usuario = usuario;
        this.pasword = pasword;
        this.estado = estado;
        this.fechaRegistro = fechaRegistro;
    }
    public Usuario(int id, Persona persona, String usuario, String pasword, String estado, Date fechaRegistro, Set usuarioPermisos) {
       this.id = id;
       this.persona = persona;
       this.usuario = usuario;
       this.pasword = pasword;
       this.estado = estado;
       this.fechaRegistro = fechaRegistro;
       this.usuarioPermisos = usuarioPermisos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPasword() {
        return this.pasword;
    }
    
    public void setPasword(String pasword) {
        this.pasword = pasword;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getUsuarioPermisos() {
        return this.usuarioPermisos;
    }
    
    public void setUsuarioPermisos(Set usuarioPermisos) {
        this.usuarioPermisos = usuarioPermisos;
    }




}


